### PR TITLE
bump node java

### PR DESCRIPTION
**Pull request by MatthewVita**

### CODE REVIEW

**Review by privateOmega — APPROVED** [review]
Sorry for the late reply. LGTM

**Comment by privateOmega** [comment]
Even though it doesn't fall in the purview of this PR, why aren't we updating other deps as well? might have some gains performance or less buggy?

**Comment by privateOmega** [comment]
Before this gets merged, you should refer to the reply I posted on #19

**Comment by MatthewVita** [comment]
@privateOmega Hope you're well. Sorry for the late reply (work/life again... mainly work). I just added a commit here that bumps our main dependencies as you suggested (good idea!). Only one had a breaking change but it was easy to adjust in the code/unit tests.

I don't want to touch the dev deps because 2 of the 3 testing packages are either deprecated or in maintenance mode... I'm happy to leave them frozen.

Please let me know if this commit checks out with you. I'll be replying to the main PR this weekend. I think I have a bit of confusion there to be honest.

**Comment by privateOmega** [comment]
@MatthewVita So sorry for not replying back to this comment, my work/life had took a turn to be crazy hectic and couldn't reply to your replies in time, I remember typing out reply to this, but must have had not clicked on the send button, but I am glad that you have merged it.

**Pull request merged**
